apiVersion: crossplanedemo.com/v1alpha1
kind: CompositeCluster
metadata:
  name: team-a
  labels:
    cluster-owner: kremer
spec:
  id: team-a
  compositionRef:
    name: cluster-aws
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    version: "1.23"
    # minNodeCount: 1
